// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

import posthog from "posthog-js";
import { generateQueryParams } from "./fetcher/query";
import transformData from "./fetcher/transform";
import OBBExcelError from "./fetcher/errors";
import excelDateToString from "./fetcher/dates";
import { privateFunc, getProviderChoice } from "./fetcher/utils";
import { sliceArray } from "./slicer";
import { createWidgetRequest, fetchWidgetRequest, getCustomBackend, getWidgetDefinition } from "~/functions/custom.api";
import { platformClient } from "~/functions/fetcher/platform.api";
import { RawCell } from "~/types/excel.types";

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Get the data from a widget living in a backend.
 * @customfunction WIDGET
 * @param backend Name of the backend.
 * @param widget Name or ID of the widget to get data for.
 * @param [parameters] Widget parameters as (n rows by 2 columns) range selection or array constant (e.g. {"key1","value1"}; {"key2","value2"}).
 * @returns Widget data.
 * @helpurl https://docs.openbb.co/excel/backends
 */
export async function widget(
  backend: string,  
  widget: string,
  parameters?: any[][],
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture("custom_function", {function: "WIDGET", params: {backend, widget, parameters}});

    const customBackend = getCustomBackend(backend);
    const widgetDefinition = await getWidgetDefinition(customBackend, widget);
    const request = createWidgetRequest(customBackend!, widgetDefinition!, parameters || [] as RawCell[][]);
    const result = await fetchWidgetRequest(request);
    
    let data: any;
    if (request.dataKey) data = result[request.dataKey];
    else data = result;
    return transformData(data);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("WIDGET", widget);

/**
 * Slice data from a range.
 * @customfunction GET
 * @param array Array to slice.
 * @param [rows] Range of row labels or indices.
 * @param [columns] Range of column labels or indices.
 * @returns Sliced array.
 * @helpurl https://docs.openbb.co/excel/data-slicer
 */
export async function get(
  array: any[][],
  rows: any[][],
  columns: any[][],
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture("custom_function", {function: "GET", params: {array, rows, columns}});
    return sliceArray(array, rows, columns);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("GET", get);

/**
 * Currency Historical Price. Currency historical data.

Currency historical prices refer to the past exchange rates of one currency against
another over a specific period.
This data provides insight into the fluctuations and trends in the foreign exchange market,
helping analysts, traders, and economists understand currency performance,
evaluate economic health, and make predictions about future movements.
 * @customfunction CURRENCY.PRICE.HISTORICAL
 * @param symbol Symbol to get data for. Can use CURR1-CURR2 or CURR1CURR2 format. Multiple comma separated items allowed.
 * @param [start_date] Start date of the data, in YYYY-MM-DD format.
 * @param [end_date] End date of the data, in YYYY-MM-DD format.
 * @param [interval] Time interval of the data to return. Options: 1m, 5m, 15m, 30m, 1h, 4h, 1d.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/currency/price/historical
 */
export async function currency_price_historical(
  symbol: string,
  start_date?: string,
  end_date?: string,
  interval?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'CURRENCY.PRICE.HISTORICAL', params: {symbol, start_date, end_date, interval, }});
    const providerChoice = await getProviderChoice("currency_price_historical", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["start_date", excelDateToString(start_date), ""],
      ["end_date", excelDateToString(end_date), ""],
      ["interval", interval, "1d"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/currency/price/historical?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("CURRENCY.PRICE.HISTORICAL", currency_price_historical);

/**
 * Snapshots of currency exchange rates from an indirect or direct perspective of a base currency.
 * @customfunction CURRENCY.SNAPSHOTS
 * @param [base] The base currency symbol. Multiple comma separated items allowed.
 * @param [quote_type] Whether the quote is direct or indirect. Selecting 'direct' will return the exchange rate as the amount of domestic currency required to buy one unit of the foreign currency. Selecting 'indirect' (default) will return the exchange rate as the amount of foreign currency required to buy one unit of the domestic currency.
 * @param [counter_currencies] An optional list of counter currency symbols to filter for. None returns all.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/currency/snapshots
 */
export async function currency_snapshots(
  base?: string,
  quote_type?: string,
  counter_currencies?: any[][] | string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'CURRENCY.SNAPSHOTS', params: {base, quote_type, counter_currencies, }});
    const providerChoice = await getProviderChoice("currency_snapshots", "fmp")
    const queryParams = generateQueryParams([
      ["base", base, "usd"],
      ["quote_type", quote_type, "indirect"],
      ["counter_currencies", counter_currencies, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/currency/snapshots?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("CURRENCY.SNAPSHOTS", currency_snapshots);

/**
 * Get the complete options chain for a ticker.
 * @customfunction DERIVATIVES.OPTIONS.CHAINS
 * @param symbol Symbol to get data for.
 * @param [date] The end-of-day date for options chains data.
 * @param [option_type] The option type, call or put, 'None' is both (default). Options: call, put.
 * @param [moneyness] Return only contracts that are in or out of the money, default is 'all'. Parameter is ignored when a date is supplied. Options: otm, itm, all.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/derivatives/options/chains
 */
export async function derivatives_options_chains(
  symbol: string,
  date?: string,
  option_type?: string,
  moneyness?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'DERIVATIVES.OPTIONS.CHAINS', params: {symbol, date, option_type, moneyness, }});
    const providerChoice = await getProviderChoice("derivatives_options_chains", "intrinio")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["date", excelDateToString(date), ""],
      ["option_type", option_type, ""],
      ["moneyness", moneyness, "all"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/derivatives/options/chains?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("DERIVATIVES.OPTIONS.CHAINS", derivatives_options_chains);

/**
 * Get a profile of country statistics and economic indicators.
 * @customfunction ECONOMY.COUNTRY_PROFILE
 * @param country The country to get data. Multiple comma separated items allowed.
 * @param [latest] If True, return only the latest data. If False, return all available data for each indicator.
 * @param [use_cache] If True, the request will be cached for one day.Using cache is recommended to avoid needlessly requesting the same data.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/economy/country_profile
 */
export async function economy_country_profile(
  country: string,
  latest?: boolean,
  use_cache?: boolean,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'ECONOMY.COUNTRY_PROFILE', params: {country, latest, use_cache, }});
    const providerChoice = await getProviderChoice("economy_country_profile", "econdb")
    const queryParams = generateQueryParams([
      ["country", country, ""],
      ["latest", latest, "True"],
      ["use_cache", use_cache, "True"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/economy/country_profile?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("ECONOMY.COUNTRY_PROFILE", economy_country_profile);

/**
 * Get economic indicators by country and indicator.
 * @customfunction ECONOMY.INDICATORS
 * @param symbol Symbol to get data for. The base symbol for the indicator (e.g. GDP, CPI, etc.). Multiple comma separated items allowed.
 * @param [country] The country to get data. The country represented by the indicator, if available. Multiple comma separated items allowed.
 * @param [start_date] Start date of the data, in YYYY-MM-DD format.
 * @param [end_date] End date of the data, in YYYY-MM-DD format.
 * @param [transform] tusd` should only be used where values are currencies. Options: toya, tpop, tusd, tpgp.
 * @param [frequency] The frequency of the data, default is 'quarter'. Only valid when 'symbol' is 'main'. Options: annual, quarter, month.
 * @param [use_cache] If True, the request will be cached for one day. Using cache is recommended to avoid needlessly requesting the same data.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/economy/indicators
 */
export async function economy_indicators(
  symbol: string,
  country?: string,
  start_date?: string,
  end_date?: string,
  transform?: string,
  frequency?: string,
  use_cache?: boolean,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'ECONOMY.INDICATORS', params: {symbol, country, start_date, end_date, transform, frequency, use_cache, }});
    const providerChoice = await getProviderChoice("economy_indicators", "econdb")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["country", country, ""],
      ["start_date", excelDateToString(start_date), ""],
      ["end_date", excelDateToString(end_date), ""],
      ["transform", transform, ""],
      ["frequency", frequency, "quarter"],
      ["use_cache", use_cache, "True"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/economy/indicators?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("ECONOMY.INDICATORS", economy_indicators);

/**
 * Get the closest peers for a given company.

Peers consist of companies trading on the same exchange, operating within the same sector
and with comparable market capitalizations.
 * @customfunction EQUITY.COMPARE.PEERS
 * @param symbol Symbol to get data for.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/compare/peers
 */
export async function equity_compare_peers(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.COMPARE.PEERS', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_compare_peers", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/compare/peers?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.COMPARE.PEERS", equity_compare_peers);

/**
 * Get consensus price target and recommendation.
 * @customfunction EQUITY.ESTIMATES.CONSENSUS
 * @param [symbol] Symbol to get data for. Multiple comma separated items allowed.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/estimates/consensus
 */
export async function equity_estimates_consensus(
  symbol?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.ESTIMATES.CONSENSUS', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_estimates_consensus", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/estimates/consensus?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.ESTIMATES.CONSENSUS", equity_estimates_consensus);

/**
 * Get forward EBITDA estimates.
 * @customfunction EQUITY.ESTIMATES.FORWARD_EBITDA
 * @param [symbol] Symbol to get data for. Multiple comma separated items allowed.
 * @param [fiscal_period] The future fiscal period to retrieve estimates for. Options: annual, quarter.
 * @param [limit] The number of data entries to return.
 * @param [include_historical] If True, the data will include all past data and the limit will be ignored.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/estimates/forward_ebitda
 */
export async function equity_estimates_forward_ebitda(
  symbol?: string,
  fiscal_period?: string,
  limit?: number,
  include_historical?: boolean,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.ESTIMATES.FORWARD_EBITDA', params: {symbol, fiscal_period, limit, include_historical, }});
    const providerChoice = await getProviderChoice("equity_estimates_forward_ebitda", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["fiscal_period", fiscal_period, "annual"],
      ["limit", limit, "500"],
      ["include_historical", include_historical, "False"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/estimates/forward_ebitda?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.ESTIMATES.FORWARD_EBITDA", equity_estimates_forward_ebitda);

/**
 * Get analyst price targets by company.
 * @customfunction EQUITY.ESTIMATES.PRICE_TARGET
 * @param [symbol] Symbol to get data for. Multiple comma separated items allowed.
 * @param [limit] The number of data entries to return.
 * @param [with_grade] Include upgrades and downgrades in the response.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/estimates/price_target
 */
export async function equity_estimates_price_target(
  symbol?: string,
  limit?: number,
  with_grade?: boolean,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.ESTIMATES.PRICE_TARGET', params: {symbol, limit, with_grade, }});
    const providerChoice = await getProviderChoice("equity_estimates_price_target", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["limit", limit, "200"],
      ["with_grade", with_grade, "False"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/estimates/price_target?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.ESTIMATES.PRICE_TARGET", equity_estimates_price_target);

/**
 * Get the balance sheet for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.BALANCE
 * @param symbol Symbol to get data for.
 * @param [period] Time period of the data to return.
 * @param [limit] The number of data entries to return.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/balance
 */
export async function equity_fundamental_balance(
  symbol: string,
  period?: string,
  limit?: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.BALANCE', params: {symbol, period, limit, }});
    const providerChoice = await getProviderChoice("equity_fundamental_balance", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["limit", limit, "5"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/balance?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.BALANCE", equity_fundamental_balance);

/**
 * Get the cash flow statement for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.CASH
 * @param symbol Symbol to get data for.
 * @param [period] Time period of the data to return.
 * @param [limit] The number of data entries to return.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/cash
 */
export async function equity_fundamental_cash(
  symbol: string,
  period?: string,
  limit?: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.CASH', params: {symbol, period, limit, }});
    const providerChoice = await getProviderChoice("equity_fundamental_cash", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["limit", limit, "5"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/cash?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.CASH", equity_fundamental_cash);

/**
 * Get historical dividend data for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.DIVIDENDS
 * @param symbol Symbol to get data for.
 * @param [start_date] Start date of the data, in YYYY-MM-DD format.
 * @param [end_date] End date of the data, in YYYY-MM-DD format.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/dividends
 */
export async function equity_fundamental_dividends(
  symbol: string,
  start_date?: string,
  end_date?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.DIVIDENDS', params: {symbol, start_date, end_date, }});
    const providerChoice = await getProviderChoice("equity_fundamental_dividends", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["start_date", excelDateToString(start_date), ""],
      ["end_date", excelDateToString(end_date), ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/dividends?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.DIVIDENDS", equity_fundamental_dividends);

/**
 * Get the URLs to SEC filings reported to EDGAR database, such as 10-K, 10-Q, 8-K, and more. SEC
filings include Form 10-K, Form 10-Q, Form 8-K, the proxy statement, Forms 3, 4, and 5, Schedule 13, Form 114,
Foreign Investment Disclosures and others. The annual 10-K report is required to be
filed annually and includes the company's financial statements, management discussion and analysis,
and audited financial statements.
 * @customfunction EQUITY.FUNDAMENTAL.FILINGS
 * @param [symbol] Symbol to get data for.
 * @param [form_type] Filter by form type. Check the data provider for available types.
 * @param [limit] The number of data entries to return.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/filings
 */
export async function equity_fundamental_filings(
  symbol?: string,
  form_type?: string,
  limit?: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.FILINGS', params: {symbol, form_type, limit, }});
    const providerChoice = await getProviderChoice("equity_fundamental_filings", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["form_type", form_type, ""],
      ["limit", limit, "100"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/filings?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.FILINGS", equity_fundamental_filings);

/**
 * Get historical earnings per share data for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.HISTORICAL_EPS
 * @param symbol Symbol to get data for.
 * @param [limit] The number of data entries to return.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/historical_eps
 */
export async function equity_fundamental_historical_eps(
  symbol: string,
  limit?: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.HISTORICAL_EPS', params: {symbol, limit, }});
    const providerChoice = await getProviderChoice("equity_fundamental_historical_eps", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["limit", limit, "500"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/historical_eps?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.HISTORICAL_EPS", equity_fundamental_historical_eps);

/**
 * Get historical stock splits for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.HISTORICAL_SPLITS
 * @param symbol Symbol to get data for.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/historical_splits
 */
export async function equity_fundamental_historical_splits(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.HISTORICAL_SPLITS', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_fundamental_historical_splits", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/historical_splits?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.HISTORICAL_SPLITS", equity_fundamental_historical_splits);

/**
 * Get the income statement for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.INCOME
 * @param symbol Symbol to get data for.
 * @param [period] Time period of the data to return.
 * @param [limit] The number of data entries to return.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/income
 */
export async function equity_fundamental_income(
  symbol: string,
  period?: string,
  limit?: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.INCOME', params: {symbol, period, limit, }});
    const providerChoice = await getProviderChoice("equity_fundamental_income", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["limit", limit, "5"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/income?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.INCOME", equity_fundamental_income);

/**
 * Get executive management team data for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.MANAGEMENT
 * @param symbol Symbol to get data for.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/management
 */
export async function equity_fundamental_management(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.MANAGEMENT', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_fundamental_management", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/management?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.MANAGEMENT", equity_fundamental_management);

/**
 * Get fundamental metrics for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.METRICS
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @param [period] Time period of the data to return.
 * @param [limit] The number of data entries to return.
 * @param [with_ttm] Include trailing twelve months (TTM) data.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/metrics
 */
export async function equity_fundamental_metrics(
  symbol: string,
  period?: string,
  limit?: number,
  with_ttm?: boolean,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.METRICS', params: {symbol, period, limit, with_ttm, }});
    const providerChoice = await getProviderChoice("equity_fundamental_metrics", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["limit", limit, "100"],
      ["with_ttm", with_ttm, "False"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/metrics?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.METRICS", equity_fundamental_metrics);

/**
 * Get company general business and stock data for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.OVERVIEW
 * @param symbol Symbol to get data for.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/overview
 */
export async function equity_fundamental_overview(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.OVERVIEW', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_fundamental_overview", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/overview?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.OVERVIEW", equity_fundamental_overview);

/**
 * Get an extensive set of financial and accounting ratios for a given company over time.
 * @customfunction EQUITY.FUNDAMENTAL.RATIOS
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @param [period] Time period of the data to return.
 * @param [limit] The number of data entries to return.
 * @param [with_ttm] Include trailing twelve months (TTM) data.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/ratios
 */
export async function equity_fundamental_ratios(
  symbol: string,
  period?: string,
  limit?: number,
  with_ttm?: boolean,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.RATIOS', params: {symbol, period, limit, with_ttm, }});
    const providerChoice = await getProviderChoice("equity_fundamental_ratios", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["limit", limit, "12"],
      ["with_ttm", with_ttm, "False"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/ratios?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.RATIOS", equity_fundamental_ratios);

/**
 * Get the revenue geographic breakdown for a given company over time.
 * @customfunction EQUITY.FUNDAMENTAL.REVENUE_PER_GEOGRAPHY
 * @param symbol Symbol to get data for.
 * @param [period] Time period of the data to return.
 * @param [structure] Structure of the returned data.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/revenue_per_geography
 */
export async function equity_fundamental_revenue_per_geography(
  symbol: string,
  period?: string,
  structure?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.REVENUE_PER_GEOGRAPHY', params: {symbol, period, structure, }});
    const providerChoice = await getProviderChoice("equity_fundamental_revenue_per_geography", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["structure", structure, "flat"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/revenue_per_geography?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.REVENUE_PER_GEOGRAPHY", equity_fundamental_revenue_per_geography);

/**
 * Get the revenue breakdown by business segment for a given company over time.
 * @customfunction EQUITY.FUNDAMENTAL.REVENUE_PER_SEGMENT
 * @param symbol Symbol to get data for.
 * @param [period] Time period of the data to return.
 * @param [structure] Structure of the returned data.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/revenue_per_segment
 */
export async function equity_fundamental_revenue_per_segment(
  symbol: string,
  period?: string,
  structure?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.REVENUE_PER_SEGMENT', params: {symbol, period, structure, }});
    const providerChoice = await getProviderChoice("equity_fundamental_revenue_per_segment", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["period", period, "annual"],
      ["structure", structure, "flat"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/revenue_per_segment?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.REVENUE_PER_SEGMENT", equity_fundamental_revenue_per_segment);

/**
 * Get earnings call transcripts for a given company.
 * @customfunction EQUITY.FUNDAMENTAL.TRANSCRIPT
 * @param symbol Symbol to get data for.
 * @param year Year of the earnings call transcript.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/fundamental/transcript
 */
export async function equity_fundamental_transcript(
  symbol: string,
  year: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.FUNDAMENTAL.TRANSCRIPT', params: {symbol, year, }});
    const providerChoice = await getProviderChoice("equity_fundamental_transcript", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["year", year, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/fundamental/transcript?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.FUNDAMENTAL.TRANSCRIPT", equity_fundamental_transcript);

/**
 * Get data about trading by a company's management team and board of directors.
 * @customfunction EQUITY.OWNERSHIP.INSIDER_TRADING
 * @param symbol Symbol to get data for.
 * @param [limit] The number of data entries to return.
 * @param [transactionType] Type of the transaction. Options: award, conversion, return, expire_short, in_kind, gift, expire_long, discretionary, other, small, exempt, otm, purchase, sale, tender, will, itm, trust.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/ownership/insider_trading
 */
export async function equity_ownership_insider_trading(
  symbol: string,
  limit?: number,
  transactionType?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.OWNERSHIP.INSIDER_TRADING', params: {symbol, limit, transactionType, }});
    const providerChoice = await getProviderChoice("equity_ownership_insider_trading", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["limit", limit, "500"],
      ["transactionType", transactionType, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/ownership/insider_trading?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.OWNERSHIP.INSIDER_TRADING", equity_ownership_insider_trading);

/**
 * Get data about institutional ownership for a given company over time.
 * @customfunction EQUITY.OWNERSHIP.INSTITUTIONAL
 * @param symbol Symbol to get data for.
 * @param [include_current_quarter] Include current quarter data.
 * @param [date] A specific date to get data for.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/ownership/institutional
 */
export async function equity_ownership_institutional(
  symbol: string,
  include_current_quarter?: boolean,
  date?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.OWNERSHIP.INSTITUTIONAL', params: {symbol, include_current_quarter, date, }});
    const providerChoice = await getProviderChoice("equity_ownership_institutional", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["include_current_quarter", include_current_quarter, "False"],
      ["date", excelDateToString(date), ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/ownership/institutional?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.OWNERSHIP.INSTITUTIONAL", equity_ownership_institutional);

/**
 * Get data about major holders for a given company over time.
 * @customfunction EQUITY.OWNERSHIP.MAJOR_HOLDERS
 * @param symbol Symbol to get data for.
 * @param [date] A specific date to get data for.
 * @param [page] Page number of the data to fetch.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/ownership/major_holders
 */
export async function equity_ownership_major_holders(
  symbol: string,
  date?: string,
  page?: number,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.OWNERSHIP.MAJOR_HOLDERS', params: {symbol, date, page, }});
    const providerChoice = await getProviderChoice("equity_ownership_major_holders", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["date", excelDateToString(date), ""],
      ["page", page, "0"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/ownership/major_holders?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.OWNERSHIP.MAJOR_HOLDERS", equity_ownership_major_holders);

/**
 * Get data about share float for a given company.
 * @customfunction EQUITY.OWNERSHIP.SHARE_STATISTICS
 * @param symbol Symbol to get data for.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/ownership/share_statistics
 */
export async function equity_ownership_share_statistics(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.OWNERSHIP.SHARE_STATISTICS', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_ownership_share_statistics", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/ownership/share_statistics?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.OWNERSHIP.SHARE_STATISTICS", equity_ownership_share_statistics);

/**
 * Get historical price data for a given stock. This includes open, high, low, close, and volume.
 * @customfunction EQUITY.PRICE.HISTORICAL
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @param [interval] Time interval of the data to return.
 * @param [start_date] Start date of the data, in YYYY-MM-DD format.
 * @param [end_date] End date of the data, in YYYY-MM-DD format.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/price/historical
 */
export async function equity_price_historical(
  symbol: string,
  interval?: string,
  start_date?: string,
  end_date?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.PRICE.HISTORICAL', params: {symbol, interval, start_date, end_date, }});
    const providerChoice = await getProviderChoice("equity_price_historical", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["interval", interval, "1d"],
      ["start_date", excelDateToString(start_date), ""],
      ["end_date", excelDateToString(end_date), ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/price/historical?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.PRICE.HISTORICAL", equity_price_historical);

/**
 * Get price performance data for a given stock. This includes price changes for different time periods.
 * @customfunction EQUITY.PRICE.PERFORMANCE
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/price/performance
 */
export async function equity_price_performance(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.PRICE.PERFORMANCE', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_price_performance", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/price/performance?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.PRICE.PERFORMANCE", equity_price_performance);

/**
 * Get the latest quote for a given stock. Quote includes price, volume, and other data.
 * @customfunction EQUITY.PRICE.QUOTE
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/price/quote
 */
export async function equity_price_quote(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.PRICE.QUOTE', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_price_quote", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/price/quote?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.PRICE.QUOTE", equity_price_quote);

/**
 * Get general information about a company. This includes company name, industry, sector and price data.
 * @customfunction EQUITY.PROFILE
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/equity/profile
 */
export async function equity_profile(
  symbol: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'EQUITY.PROFILE', params: {symbol, }});
    const providerChoice = await getProviderChoice("equity_profile", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/equity/profile?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("EQUITY.PROFILE", equity_profile);

/**
 * Get yield curve data by country and date.
 * @customfunction FIXEDINCOME.GOVERNMENT.YIELD_CURVE
 * @param [date] A specific date to get data for. By default is the current data. Multiple comma separated items allowed.
 * @param [use_cache] If true, cache the request for four hours.
 * @param [country] The country to get data. New Zealand, Mexico, Singapore, and Thailand have only monthly data. The nearest date to the requested one will be used. Options: australia, canada, china, hong_kong, india, japan, mexico, new_zealand, russia, saudi_arabia, singapore, south_africa, south_korea, taiwan, thailand, united_kingdom, united_states.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/fixedincome/government/yield_curve
 */
export async function fixedincome_government_yield_curve(
  date?: string,
  use_cache?: boolean,
  country?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'FIXEDINCOME.GOVERNMENT.YIELD_CURVE', params: {date, use_cache, country, }});
    const providerChoice = await getProviderChoice("fixedincome_government_yield_curve", "econdb")
    const queryParams = generateQueryParams([
      ["date", excelDateToString(date), ""],
      ["use_cache", use_cache, "True"],
      ["country", country, "united_states"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/fixedincome/government/yield_curve?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("FIXEDINCOME.GOVERNMENT.YIELD_CURVE", fixedincome_government_yield_curve);

/**
 * Get Historical Market Indices.
 * @customfunction INDEX.MARKET
 * @param symbol Symbol to get data for. Multiple comma separated items allowed.
 * @param [start_date] Start date of the data, in YYYY-MM-DD format.
 * @param [end_date] End date of the data, in YYYY-MM-DD format.
 * @param [interval] Time interval of the data to return.
 * @returns Excel array.
 * @helpurl https://docs.openbb.co/excel/reference/index/market
 */
export async function index_market(
  symbol: string,
  start_date?: string,
  end_date?: string,
  interval?: string,
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture('custom_function', {custom_function: 'INDEX.MARKET', params: {symbol, start_date, end_date, interval, }});
    const providerChoice = await getProviderChoice("index_market", "fmp")
    const queryParams = generateQueryParams([
      ["symbol", symbol, ""],
      ["start_date", excelDateToString(start_date), ""],
      ["end_date", excelDateToString(end_date), ""],
      ["interval", interval, "1d"],
      ["provider", providerChoice, providerChoice],
    ]);
    const { data } = await platformClient.get(`/api/v1/index/market?${queryParams}`);
    return transformData(data?.results);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("INDEX.MARKET", index_market);
