"""Generate typescript file from metadata"""

import os
import json
from pathlib import Path
import sys
from typing import Any, Dict, List, Optional
from dotenv import dotenv_values

from spec_generator import SpecGenerator

_ENV_FILE = ".env.local"

HELP_URL = dotenv_values(_ENV_FILE)["VITE_HELP_URL"]

CF_HEADER = """// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
"""

CF_IMPORTS = """
import posthog from "posthog-js";
import { generateQueryParams } from "./fetcher/query";
import transformData from "./fetcher/transform";
import OBBExcelError from "./fetcher/errors";
import excelDateToString from "./fetcher/dates";
import { privateFunc, getProviderChoice } from "./fetcher/utils";
import { sliceArray } from "./slicer";
import { createWidgetRequest, fetchWidgetRequest, getCustomBackend, getWidgetDefinition } from "~/functions/custom.api";
import { platformClient } from "~/functions/fetcher/platform.api";
import { RawCell } from "~/types/excel.types";
"""

TEST_IMPORTS = """import * as utils from "~/functions/fetcher/utils";
import * as OBB from "~/functions/functions";
import { checkExpected, customSerializer, getPlatformAccessToken } from "./utils";
import { useAuthStore } from "~/store/auth";
"""

CF_COMMON = """
/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Get the data from a widget living in a backend.
 * @customfunction WIDGET
 * @param backend Name of the backend.
 * @param widget Name or ID of the widget to get data for.
 * @param [parameters] Widget parameters as (n rows by 2 columns) range selection or array constant (e.g. {"key1","value1"}; {"key2","value2"}).
 * @returns Widget data.
 * @helpurl https://docs.openbb.co/excel/backends
 */
export async function widget(
  backend: string,  
  widget: string,
  parameters?: any[][],
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture("custom_function", {function: "WIDGET", params: {backend, widget, parameters}});

    const customBackend = getCustomBackend(backend);
    const widgetDefinition = await getWidgetDefinition(customBackend, widget);
    const request = createWidgetRequest(customBackend!, widgetDefinition!, parameters || [] as RawCell[][]);
    const result = await fetchWidgetRequest(request);
    
    let data: any;
    if (request.dataKey) data = result[request.dataKey];
    else data = result;
    return transformData(data);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("WIDGET", widget);

/**
 * Slice data from a range.
 * @customfunction GET
 * @param array Array to slice.
 * @param [rows] Range of row labels or indices.
 * @param [columns] Range of column labels or indices.
 * @returns Sliced array.
 * @helpurl https://docs.openbb.co/excel/data-slicer
 */
export async function get(
  array: any[][],
  rows: any[][],
  columns: any[][],
): Promise<any[][]> {
  try {
    privateFunc();
    posthog.capture("custom_function", {function: "GET", params: {array, rows, columns}});
    return sliceArray(array, rows, columns);
  } catch (e) {
    return OBBExcelError(e);
  }
}
CustomFunctions.associate("GET", get);
"""


class TSGenerator:
    """This class generates TypeScript code: custom functions and tests."""

    prefix = "/api/v1/"
    parent_dir = os.path.join(Path(__file__).parent)
    default_funcs_file = Path(parent_dir, "..", "functions.ts")
    default_tests_file = Path(
        parent_dir, "..", "..", "..", "tests", "integration", "functions.full.test.ts"
    )

    def __init__(
        self,
        funcs_file: Optional[Path] = None,
        tests_file: Optional[Path] = None,
    ) -> None:
        self.funcs_file = funcs_file or self.default_funcs_file
        self.tests_file = tests_file or self.default_tests_file
        self.openbb_functions: Dict[str, Dict[str]] = {}

    @staticmethod
    def read(file: Path) -> dict:
        """Read data from file."""
        try:
            with open(file, "r", encoding="utf-8") as f:
                return json.load(f)
        except FileNotFoundError:
            print(f"File {file} not found.\n")
            return {}

    @staticmethod
    def remove(files: List[Path]):
        """Remove files"""
        for file in files:
            if file.exists():
                file.unlink()

    @staticmethod
    def write(code: str, file: Path):
        """Write to file"""
        with open(file, "a+", encoding="utf-8") as f:
            f.write(code)

    @staticmethod
    def dump(data: Any, file: Path):
        """Dump data to file"""
        with open(file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)

    def generate_docstring(
        self,
        description: str,
        parameters: List[Dict[str, Any]],
        returns: str,
        name: str,
        help_url: str,
    ) -> str:
        """Generate docstring."""

        code = "\n/**\n"
        code += f" * {description}"
        code += f"\n * @customfunction {name}\n"
        for p in parameters:
            p_name = p.get("name", "")
            p_desc = p.get("description", "")
            p_optional = p.get("optional", True)
            param = f"[{p_name}]" if p_optional else p_name
            code += f" * @param {param} {p_desc}\n"
        code += f" * @returns {returns}\n"
        code += f" * @helpurl {help_url}\n"
        code += " */\n"
        return code

    def generate_signature(
        self, func_name: str, parameters: List[Dict[str, Any]]
    ) -> str:
        """Generate signature."""
        code = f"export async function {func_name}(\n"
        for p in parameters:
            p_optional = "?" if p.get("optional", "") else ""
            code += f"  {p['name']}{p_optional}: {p['type_']},\n"
        code += "): Promise<any[][]> {\n"
        return code

    def generate_body(
        self,
        custom_function: str,
        parameters: List[Dict[str, Any]],
        endpoint: str,
        method: str,
        providers: List[str],
    ) -> str:
        """Generate body"""

        def get_param_value(parameter: dict) -> str:
            """Get parameter value"""
            p_name = parameter["name"]
            if p_name in ("start_date", "end_date", "date"):
                return f"excelDateToString({p_name})"
            return p_name

        code = "  try {\n"
        code += "    privateFunc();\n"
        code += f"    posthog.capture('custom_function', {{custom_function: '{custom_function}', params: {{"
        for p in parameters:
            p_name = p["name"]
            code += f"{p_name}, "
        code += "}});\n"
        parameterNames = [p["name"] for p in parameters]
        custom_function_name = custom_function.replace(".", "_").lower()
        if "provider" in parameterNames:
            code += f'    const providerChoice = provider ?? await getProviderChoice("{custom_function_name}", provider)\n'
        else:
            code += f'    const providerChoice = await getProviderChoice("{custom_function_name}", "{providers[0]}")\n'
        url_code = "    const queryParams = generateQueryParams([\n"
        for p in parameters:
            p_name = p["name"]
            p_value = get_param_value(p) if p_name != "provider" else "providerChoice"
            p_default = p["default"]
            url_code += f'      ["{p_name}", {p_value}, "{p_default}"],\n'

        if "provider" in parameterNames:
            url_code += '      ["provider", providerChoice, providerChoice],\n'
        else:
            url_code += '      ["provider", providerChoice, providerChoice],\n'

        url_code += "    ]);\n"

        code += url_code
        code += f'    const {{ data }} = await platformClient.get(`{endpoint}?${{queryParams}}`);\n'  # noqa: E501
        code += "    return transformData(data?.results);\n"
        code += "  } catch (e) {\n"
        code += "    return OBBExcelError(e);\n"
        code += "  }\n"
        code += "}\n"
        return code

    def generate_associate(self, custom_function: str, func_name: str) -> str:
        """Generate associate"""
        return f'CustomFunctions.associate("{custom_function}", {func_name});\n'

    def generate_custom_functions(self, spec: List[dict]):
        """Generate custom functions code"""
        code = CF_HEADER
        code += CF_IMPORTS
        code += CF_COMMON
        for f in spec:
            description = f["description"]
            parameters = f["parameters"]
            name = f["name"]
            endpoint = f["body"]["endpoint"]
            method = f["body"]["method"]
            help_url = f["helpUrl"]
            providers = f["providers"]
            ts_func_name = name.replace(".", "_").lower()
            code += self.generate_docstring(
                description, parameters, "Excel array.", name, help_url
            )
            code += self.generate_signature(ts_func_name, parameters)
            code += self.generate_body(name, parameters, endpoint, method, providers)
            code += self.generate_associate(name, ts_func_name)
            self.openbb_functions[name] = {"providers": providers}
        return code

    def generate_tests(self, spec: List[dict]):
        """Generate tests"""
        code = TEST_IMPORTS + "\n"
        code += """// We pass null for unused arguments to mimic Excel's behavior

describe("fullTests", () => {

  let privateFuncMock;
  let mockUseAuthStore;
  let accessToken;

  beforeAll(async () => {
    expect.addSnapshotSerializer(customSerializer(1));
    privateFuncMock = jest.spyOn(utils, "privateFunc");
    accessToken = await getPlatformAccessToken();
  }, 10000); // Timeout of 10 seconds

  beforeEach(() => {
    privateFuncMock = jest.spyOn(utils, "privateFunc");
    privateFuncMock.mockImplementation(() => {
      return accessToken;
    });
    
    mockUseAuthStore = jest.spyOn(useAuthStore, "getState");
    mockUseAuthStore.mockImplementation(() => ({
      user: {
        uuid: "",
        email: "",
        username: "",
        access_token: accessToken,
        expiration_date: "2100-09-01T00:00:00.000Z",
      },
      login: jest.fn(),
      logout: jest.fn(),
    }));
  });

  afterEach(() => {
    privateFuncMock.mockRestore();
    mockUseAuthStore.mockRestore();
  });\n\n"""
        for f in spec:
            sig_parameters = f["parameters"]
            examples = f.get("examples", [])
            name = f["name"]

            ex_code = ""
            for i, ex in enumerate(examples):
                ex_code += (
                    f"      test('Example {i} [{ex['description']}]', async () => {{\n"
                )
                ex_code += f"        const received = await OBB.{name.replace('.', '_').lower()}("
                ex_parameters = ex.get("parameters", {})
                for p in sig_parameters:
                    p_name = p.get("name")
                    p_type = p["type_"]
                    if p_name in ex_parameters:
                        if "string" in p_type:
                            ex_code += f'"{ex_parameters[p_name]}",'
                        elif "boolean" in p_type:
                            p_type = "true" if bool(ex_parameters[p_name]) else "false"
                            ex_code += f"{p_type},"
                        else:
                            ex_code += f"{ex_parameters[p_name]},"
                    else:
                        # We send null to mimic Excel's behavior
                        ex_code += "null,"
                ex_code = ex_code.strip(",")
                ex_code += ")\n"
                ex_code += "        expect(privateFuncMock).toBeCalledTimes(1);\n"
                ex_code += "        checkExpected({received});\n"
                ex_code += "      });\n"
            if ex_code:
                code += f"  describe('OBB.{name}', () => {{\n"
                code += ex_code
                code += "  });\n"
        code += "});\n"
        return code

    def generate(self, spec: List[dict]):
        """Generate code"""
        self.remove([self.funcs_file, self.tests_file])
        self.write(self.generate_custom_functions(spec), self.funcs_file)
        self.write(self.generate_tests(spec), self.tests_file)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--update":
        env = dotenv_values(_ENV_FILE) or {}
        if host := env["VITE_PLATFORM_URL"]:
            SpecGenerator.fetch_openapi(host)
        if github_pat := env["GITHUB_PAT"]:
            SpecGenerator.fetch_widgets(github_pat)
        

    spec_gen = SpecGenerator()
    spec_ = spec_gen.generate()

    ts_gen = TSGenerator()
    ts_gen.generate(spec_)
    ts_gen.dump(
        data=ts_gen.openbb_functions, file=Path("public", "assets", "openbb-functions.json")
    )
    ts_gen.dump(data=spec_, file=Path(ts_gen.parent_dir, "spec.json"))
